import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { readFile } from "node:fs/promises";

import Fastify from "fastify";
import fastifyStatic from "@fastify/static";
import fastifyCompress from "@fastify/compress";
import fastifyHelmet from "@fastify/helmet";
import fastifyCookie from "@fastify/cookie";
import fastifyRateLimit from "@fastify/rate-limit";
import fastifyWebsocket from "@fastify/websocket";

import config from "./config.js";
import { migrate } from "./db/migrate.js";
import { closePool, isDbAvailable, isDbEnabled } from "./db/pool.js";
import {
  loadSettings,
  getSettings,
  isMaintenance,
  startSettingsReloader,
  stopSettingsReloader,
} from "./lib/settings.js";

import registerApiRoutes from "./routes/api.js";
import registerAdminRoutes from "./routes/admin.js";
import registerPageRoutes from "./routes/pages.js";
import { registerRealtime, shutdownRealtime } from "./realtime/hub.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");
const PUBLIC_DIR = join(ROOT, "public");

/* Build-time CSP hashes for the inline <script> blocks (page config + JSON-LD).
   Generated by scripts/build-assets.mjs. Falling back to 'unsafe-inline' keeps
   `npm run dev` working before the first build. */
async function loadCspScriptSources() {
  try {
    const raw = await readFile(join(HERE, "generated", "csp-hashes.json"), "utf8");
    const hashes = JSON.parse(raw);
    if (Array.isArray(hashes) && hashes.length) return hashes;
  } catch {
    /* not built yet */
  }
  if (config.isProd) {
    console.warn(
      "[csp] no build-time script hashes found — falling back to 'unsafe-inline'. " +
        "Run `npm run assets` during the image build to tighten this."
    );
  }
  return ["'unsafe-inline'"];
}

export async function build() {
  const app = Fastify({
    logger: config.isProd
      ? { level: "warn" }
      : { level: "info", transport: undefined },
    trustProxy: config.trustProxy,
    // Static file serving dominates; keep per-request bookkeeping minimal.
    // A trailing slash is a different URL to Google, so it must not be folded.
    routerOptions: { ignoreTrailingSlash: false },
    bodyLimit: 256 * 1024,
  });

  const scriptSrc = await loadCspScriptSources();

  await app.register(fastifyHelmet, {
    contentSecurityPolicy: {
      directives: {
        defaultSrc: ["'self'"],
        baseUri: ["'self'"],
        frameAncestors: ["'self'"],
        objectSrc: ["'none'"],
        formAction: ["'self'"],
        // The game sets inline style attributes (tile sizing, animation delays,
        // progress bar widths), so style hashing is not workable here.
        styleSrc: ["'self'", "'unsafe-inline'"],
        scriptSrc: ["'self'", "https://accounts.google.com", ...scriptSrc],
        scriptSrcAttr: ["'none'"],
        imgSrc: ["'self'", "data:", "https://lh3.googleusercontent.com"],
        fontSrc: ["'self'", "data:"],
        // Drive appData save/load + Google Identity token endpoint.
        connectSrc: [
          "'self'",
          "https://www.googleapis.com",
          "https://accounts.google.com",
          "https://oauth2.googleapis.com",
          config.siteUrl.replace(/^http/, "ws"),
        ],
        frameSrc: ["https://accounts.google.com"],
        upgradeInsecureRequests: config.isProd ? [] : null,
      },
    },
    crossOriginEmbedderPolicy: false,
    // Google Identity Services opens a popup that needs to talk back to us.
    crossOriginOpenerPolicy: { policy: "same-origin-allow-popups" },
    hsts: config.isProd
      ? { maxAge: 31_536_000, includeSubDomains: true, preload: true }
      : false,
    referrerPolicy: { policy: "strict-origin-when-cross-origin" },
  });

  await app.register(fastifyCookie, { secret: config.sessionSecret });

  // Static assets ship pre-brotlied, so compression only ever runs on JSON.
  await app.register(fastifyCompress, {
    global: false,
    encodings: ["br", "gzip"],
    threshold: 1024,
  });

  await app.register(fastifyRateLimit, {
    global: false,
    max: 120,
    timeWindow: "1 minute",
    // Behind Traefik, req.ip is already the real client because trustProxy is on.
    keyGenerator: (req) => req.ip,
  });

  await app.register(fastifyWebsocket, {
    options: {
      maxPayload: 16 * 1024,
      clientTracking: false,
      // Room traffic is small JSON frames; per-message deflate costs more CPU
      // than it saves and is the single biggest ws memory sink.
      perMessageDeflate: false,
    },
  });

  /* ---------- maintenance gate ---------- */
  app.addHook("onRequest", async (req, reply) => {
    if (!isMaintenance()) return;

    const url = req.raw.url || "";
    // Admin must stay reachable to turn maintenance back off.
    if (
      url.startsWith("/admin") ||
      url.startsWith("/healthz") ||
      url.startsWith("/src/") ||
      url.startsWith("/api/status")
    ) {
      return;
    }

    const s = getSettings();
    reply.code(503).header("Retry-After", "300");

    if (url.startsWith("/api/") || url.startsWith("/ws")) {
      return reply.send({ error: "maintenance", message: s.maintenanceMessage });
    }

    reply.type("text/html; charset=utf-8");
    return reply.send(maintenancePage(s.maintenanceMessage));
  });

  /* ---------- health ---------- */
  app.get("/healthz", { logLevel: "silent" }, async () => ({
    ok: true,
    uptime: Math.round(process.uptime()),
    db: isDbEnabled() ? (isDbAvailable() ? "up" : "down") : "disabled",
  }));

  /* ---------- application routes (registered before static) ---------- */
  await app.register(registerApiRoutes, { prefix: "/api" });
  await app.register(registerAdminRoutes, { prefix: "/admin" });
  await registerRealtime(app);
  await app.register(registerPageRoutes);

  /* ---------- static ---------- */
  await app.register(fastifyStatic, {
    root: PUBLIC_DIR,
    index: ["index.html"],
    // Serves the .br / .gz sibling written at build time when the client
    // accepts it, so the CPU cost of compression is paid once, not per request.
    preCompressed: true,
    wildcard: false,
    etag: true,
    lastModified: true,
    cacheControl: false, // set per-type below
    setHeaders(res, path) {
      if (/\.(?:js|css|txt|json|woff2?|png|jpe?g|svg|webp|ico)$/i.test(path)) {
        // Assets are requested with a ?v=<build> cache buster from the HTML,
        // so they can be treated as permanently immutable.
        res.setHeader("Cache-Control", "public, max-age=31536000, immutable");
      } else if (/\.html$/i.test(path)) {
        res.setHeader("Cache-Control", "public, max-age=0, must-revalidate");
      } else if (/\.(?:xml|webmanifest)$/i.test(path)) {
        res.setHeader("Cache-Control", "public, max-age=3600");
      } else {
        res.setHeader("Cache-Control", "public, max-age=300");
      }
    },
  });

  app.setNotFoundHandler(
    { preHandler: app.rateLimit({ max: 60, timeWindow: "1 minute" }) },
    async (req, reply) => {
      if ((req.raw.url || "").startsWith("/api/")) {
        return reply.code(404).send({ error: "not_found" });
      }
      reply.code(404).type("text/html; charset=utf-8");
      return notFoundPage();
    }
  );

  return app;
}

function shell(title, body) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex">
<title>${title}</title>
<style>
:root{color-scheme:light dark}
body{margin:0;min-height:100vh;display:grid;place-items:center;
font:16px/1.5 "Helvetica Neue",Arial,sans-serif;background:#fff;color:#1a1a1b;padding:24px}
@media(prefers-color-scheme:dark){body{background:#121213;color:#e4e6e7}}
.b{max-width:420px;text-align:center}
h1{font-size:22px;margin:0 0 10px}
p{color:#6e767d;margin:0 0 18px}
a{display:inline-block;background:#6aaa64;color:#fff;text-decoration:none;
padding:11px 18px;border-radius:9px;font-weight:700}
.t{display:flex;gap:4px;justify-content:center;margin-bottom:18px}
.t i{width:34px;height:34px;display:grid;place-items:center;border-radius:4px;
color:#fff;font-weight:800;font-style:normal}
</style></head><body><div class="b">${body}</div></body></html>`;
}

function maintenancePage(message) {
  return shell(
    "Back shortly — Wordle Unlimited",
    `<div class="t"><i style="background:#6aaa64">W</i><i style="background:#c9b458">U</i><i style="background:#787c7e">!</i></div>
<h1>Back in a few minutes</h1><p>${escapeHtml(message)}</p>`
  );
}

function notFoundPage() {
  return shell(
    "Page not found — Wordle Unlimited",
    `<div class="t"><i style="background:#787c7e">4</i><i style="background:#c9b458">0</i><i style="background:#787c7e">4</i></div>
<h1>That page is missing</h1><p>The link may be old or mistyped.</p>
<a href="/">Play Wordle Unlimited</a>`
  );
}

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]
  );
}

/* ---------- boot ---------- */
async function start() {
  // A DB that is not ready yet must not stop the game from serving.
  try {
    await migrate();
  } catch (err) {
    console.error("[boot] migration failed:", err.message);
  }
  await loadSettings();
  startSettingsReloader();

  const app = await build();

  try {
    await app.listen({ port: config.port, host: config.host });
    console.log(
      `[boot] wordleunlimited listening on ${config.host}:${config.port} ` +
        `(${config.env}, db ${isDbEnabled() ? "configured" : "disabled"})`
    );
  } catch (err) {
    console.error("[boot] listen failed:", err);
    process.exit(1);
  }

  let closing = false;
  const shutdown = async (signal) => {
    if (closing) return;
    closing = true;
    console.log(`[shutdown] ${signal} received, draining…`);
    stopSettingsReloader();
    shutdownRealtime();
    // Give in-flight requests and websocket close frames a moment to land.
    const force = setTimeout(() => process.exit(1), 10_000);
    force.unref();
    await app.close().catch(() => {});
    await closePool();
    clearTimeout(force);
    process.exit(0);
  };

  process.on("SIGTERM", () => shutdown("SIGTERM"));
  process.on("SIGINT", () => shutdown("SIGINT"));
  process.on("unhandledRejection", (err) => {
    console.error("[fatal] unhandled rejection:", err);
  });
}

const invokedDirectly =
  process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (invokedDirectly) start();
